# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Demo dotenv-vault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}
    env:
      DEMO_DOTENV_VAULT_APP: dot-env-vault-app_v0.0.1a
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['3.11.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.version}}
    - name: Install dependencies with pip-compile tool
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile requirements.in
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        python -m unittest tests/test_load_env_variables.py
        echo "APP_ENV: $APP_ENV"
      env:
        APP_ENV: ${{secrets.APP_ENV}}
        HOSTNAME: github_action_runner_host
        APP_INCOMING_CONNECTIONS: localhost
        DOCKER_REGISTRY: dummy_registry
        DEBUG: True
        DB_NAME: dummy_db
        DB_USER: dummy_db_user
        DB_PASSWORD: dummy_db_pwd
        DB_PORT: 1111
        REDIS_PORT: 2222